version: '3.3'

services:
  db:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    networks: 
      stravasweden:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: activity
      MYSQL_USER: springboot
      MYSQL_PASSWORD: springboot_password


networks: 
  stravasweden: